### ISSUE TITLE
Disable auto-launch

### ISSUE THREAD

**Issue by Satont** [searayeah/dota-camera-distance#12]
Hi, can you disable auto-lunch?

I guess it can be configurable and enabled by default if you want (i prefer disabled), but it kind of annoying when dota gets launched even i wont that RN.

**Comment by searayeah** [comment]
Hi!

The autostart function exists as a part of replacing the Dota 2 shortcut with this app and launching the game through this new shortcut. If you believe that running the program once will permanently adjust the camera distance, you are mistaken. Whenever an update is released for Dota (even a minor bug fix), all the changes are fully reset. That's why this program exists - to eliminate the need for manual adjustments every time and to simply forget about it.

But if you need that disabled for some reason, I will add this feature in the upcoming update.

**Comment by Satont** [comment]
I understand your approach, so I propose to leave the autostart on as standard, and just add a setting to turn it off.

**Comment by Satont** [comment]
Thank you very much!
